# Generated by Django 4.1.5 on 2023-02-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloblog',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
