# Generated by Django 4.1.5 on 2023-02-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articuloblog_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='articuloblog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_articulos'),
        ),
    ]
