# Generated by Django 4.1.5 on 2023-02-02 19:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articuloblog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloblog',
            name='cuerpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
